### ISSUE TITLE
mimetypes for which response to send

### ISSUE THREAD

**Issue by kurz-m** [kurz-m/webserv#12]

**Comment by flolau2k** [comment]
implemented a mimetype map in 461bec8d4c3c1e90790ccff81ca44863f942f696
Server will decide based on uri extension what to send back. 
TODO:
- sending binary data back. trying to send a jpg file fails because the buffer_.assign(istreambuf_iterator ...) does not work and the buffer stays empty.

**Comment by kurz-m** [comment]
Commits related to working mimetype ccd8827d1aeea10c0d7f21beeb0191037242d41f fdb4383bed83370b94d499016d862b5e3817a113 c5d98879ed7a06751d04bf67b925a961e560c801
