### ISSUE TITLE
read about cgi and how it works

### ISSUE THREAD

**Issue by flolau2k** [kurz-m/webserv#16]

**Comment by flolau2k** [comment]
- the cgi process is as follows: when the server gets a CGI Request (for example a file with a `.php` extension) it forks, and sends its output to the socket. 
- if in the request are parameters, for example `index.php?username=me`, these parameters will be set as environment variables for the fork.
- the server waits for the child to finish, and then goes on to the next request.

simple example: [CGI Web Server](https://w3.cs.jmu.edu/kirkpams/OpenCSF/Books/csf/html/Extended4CGI.html)

**Comment by kurz-m** [comment]
@flolau2k  now how to handle cgi ;)
