### ISSUE TITLE
check timeout after sending data

### ISSUE THREAD

**Issue by kurz-m** [kurz-m/webserv#21]
## Check for the correct timeout when a socket connects to the server
- It seems that currently the timeout is set too short
- maybe refresh the timeout after sending

**Comment by flolau2k** [comment]
fixed the timestamp update from `std::clock` to `std::time`, now it works.

**Comment by kurz-m** [comment]
Fixed in 25528a784b16e5535e290c3079341ebd4a6c1d3a

https://github.com/kurz-m/webserv/blob/25528a784b16e5535e290c3079341ebd4a6c1d3a/SocketConnect.cpp#L68-L90
