### ISSUE TITLE
parser treats locations as absolute paths while parsing

### ISSUE THREAD

**Issue by flolau2k** [kurz-m/webserv#34]
Parser treats locations as absolute paths and calls stat on them, to check if the location is valid.
Problem is, that the location paths are relative to the webroot, but stat treats them as absolute paths.
example:

`location /cgi-bin {
            allow GET;
}`

calls `stat` on `/cgi-bin`, a folder that does not exist

**Comment by kurz-m** [comment]
fixed in #51 

check are being conducted by adding root to the given location.
