### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by flolau2k** [kurz-m/webserv#40]
collection of bugs

**Comment by flolau2k** [comment]
Found a bug, server goes crazy: 


![Image](https://github.com/kurz-m/webserv/assets/44669170/6faef89e-9669-4b4b-a054-9f770792ccb2)

Steps to reproduce:
- try to load a regular file in `/cgi-bin`. server will send empty response.
- browser will keep loading.
- cancel browser

**Comment by flolau2k** [comment]
Server sends empty response when requested a regular file in `/cgi-bin`

**Comment by flolau2k** [comment]
Query Strings don't work anymore, we need to find a new method to identify CGI requests.

**Comment by kurz-m** [comment]
## Problem
- double slash in the uri causes problem with respect to finding the folders.

## How to trigger
- open up a _index-of_ page and click a folder to follow its path

![Image](https://github.com/kurz-m/webserv/assets/85294588/28369914-48cc-4da4-9a3f-3d6edf4eb9ed)

## possible fixes
- either remove double slashes already in the request/response handler
- remove double slashes only in the list dir function

**Comment by kurz-m** [comment]
When having autoindex on and no index.html, there is a problem currently with the detection of cgi calls. There we need to change the method of how to decide what it is.

**Comment by flolau2k** [comment]
when the server is waiting for a CGI child, it polls like crazy. 
steps to reproduce:
- call the sleep.py cgi file.
- watch terminal output

**Comment by kurz-m** [comment]
## Where
- config file

## What
- When there is no `;` at the end of the line, the Parser reads until the next semicolon.

## How to handle
- either throw a syntax error or just continue silently ;)

**Comment by flolau2k** [comment]
Random Memory errors on MacOS
