### ISSUE TITLE
Limit Client Max Body Size

### ISSUE THREAD

**Issue by flolau2k** [kurz-m/webserv#54]
Limit client max body size

**Comment by flolau2k** [comment]
works in principle with b0eacaf3e230dd01aa45d4c3de5dcdee458d976e
current known bugs: after sending the 413 page, it resumes the socket to `READY_RECV`. Then it will continue receiving the old, too large body.

**Comment by flolau2k** [comment]
fixed with 0d0aa14bd17dd4b30fbebfe13ea814844e003d6d
socket now keeps track of the total bytes received. plus receives completely all avaliable data to prevent the old body to hang in the buffer

**Comment by kurz-m** [comment]
fixed and merged with #60
