### ISSUE TITLE
Handle USEND correctly

### ISSUE THREAD

**Issue by flolau2k** [kurz-m/webserv#59]
> handle usend correctly. currently it would send the same bytes on second try. 
> added a todo in the code. see `send_response_()` function. 

 _Originally posted by @flolau2k in [#40](https://github.com/kurz-m/webserv/issues/40#issuecomment-2017873042)_

**Comment by flolau2k** [comment]
fixed with 1fabfd1d109eed68703fa14d1a89dc990990231e

**Comment by kurz-m** [comment]
fixed and reviewed in #61
