### ISSUE TITLE
Random Memory errors on MacOS

### ISSUE THREAD

**Issue by flolau2k** [kurz-m/webserv#70]
on MacOS the server randomly segfaults due to a corrupted `client_map_` and due to a corruption of the filedescriptor in the `poll_list_`, which is sometimes randomly `0`

> Random Memory errors on MacOS 

 _Originally posted by @flolau2k in [#40](https://github.com/kurz-m/webserv/issues/40#issuecomment-2027463841)_

**Comment by flolau2k** [comment]
apparently fixed by 23807fe364fcf63f1b633d7abd9a7d4db3ba3b0e

**Comment by kurz-m** [comment]
Fixed in #72 
Valgrind showed that freeaddrinfo cause corrupted memory in which we tried to write again. This apparently caused only problems on macOS and did not bother under Linux.
